<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-12 23:47
=======
# Generated by Django 5.1.7 on 2025-04-12 23:55
>>>>>>> 0520c1a19de59fcfd139dd692c52f2d7468e49fc

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.libraryuser'),
        ),
        migrations.AddField(
            model_name='bookloan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='management.bookcopy'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='management.librarybranch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library.book'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='management.librarybranch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.libraryuser'),
        ),
    ]
