# Generated by Django 5.1.7 on 2025-06-08 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='cod',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='series.category'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cod',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
