# Generated by Django 5.1.7 on 2025-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='in_reading_lists', to='library.category'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='in_reading_lists', to='library.book'),
        ),
    ]
