# Generated by Django 5.1.7 on 2025-03-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tasks_task',
        ),
    ]
